# Generated by Django 4.1.6 on 2023-03-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0009_delete_tbl_assignment'),
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
