# Generated by Django 4.1.6 on 2023-02-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0002_rename_tbl_studentlogin_tbl_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_login',
            name='s_id',
        ),
    ]
