# Generated by Django 4.1.6 on 2023-02-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0005_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_img', models.ImageField(null=True, upload_to='course/subject')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='SLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SLanguage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
            ],
        ),
    ]
