# Generated by Django 4.1.6 on 2023-02-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0006_course_subjects_slanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='slanguage',
            old_name='id',
            new_name='slanguage_id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='id',
            new_name='subject_id',
        ),
    ]
