# Generated by Django 4.1.6 on 2023-02-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0008_tbl_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Assignment',
        ),
    ]
