# Generated by Django 4.1.6 on 2023-03-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0009_delete_tbl_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='email',
        ),
        migrations.CreateModel(
            name='tbl_stream',
            fields=[
                ('stream_id', models.IntegerField(null=True)),
                ('stream_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
            ],
        ),
    ]
