# Generated by Django 4.1.6 on 2023-03-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Schoolapp', '0010_remove_subjects_email_tbl_stream'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentdetails',
            new_name='Studentdetail',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
