# Generated by Django 4.1.6 on 2023-03-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0011_rename_studentdetails_studentdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stream',
            name='Course_name',
        ),
        migrations.DeleteModel(
            name='SLanguage',
        ),
        migrations.DeleteModel(
            name='tbl_stream',
        ),
    ]
