# Generated by Django 4.1.6 on 2023-03-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0012_remove_tbl_stream_course_name_delete_slanguage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('hname', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(default=0, max_length=200)),
                ('dob', models.DateField()),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
            ],
        ),
    ]
