# Generated by Django 4.1.6 on 2023-03-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0015_alter_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_create_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_one', models.BooleanField(default=0)),
                ('plus_two', models.BooleanField(default=0)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.teacher_detail')),
            ],
        ),
    ]
