# Generated by Django 4.1.6 on 2023-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0016_tbl_create_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_create_class',
            name='plus_one',
            field=models.BooleanField(default=1),
        ),
    ]
