# Generated by Django 4.1.6 on 2023-03-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0018_rename_teacher_tbl_create_class_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'email__type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.teacher_detail'),
        ),
    ]
