# Generated by Django 4.1.6 on 2023-03-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0020_alter_teacher_detail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='email',
            field=models.ForeignKey(limit_choices_to={'type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
