# Generated by Django 4.1.6 on 2023-03-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0024_alter_course_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(limit_choices_to={'email__type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
