# Generated by Django 4.1.6 on 2023-04-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0026_alter_course_teacher_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studentdetail',
        ),
    ]
