# Generated by Django 4.1.6 on 2023-04-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0029_student_detail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='student/profile'),
        ),
    ]
