# Generated by Django 4.1.6 on 2023-04-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0030_student_detail_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_category', models.CharField(max_length=100, null=True)),
                ('session_division', models.CharField(max_length=100, null=True)),
                ('Class_teacher', models.ForeignKey(limit_choices_to={'email__type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Batch',
            fields=[
                ('c_class_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_name',
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'email__type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
        migrations.DeleteModel(
            name='tbl_create_class',
        ),
        migrations.AddField(
            model_name='tbl_batch',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
        ),
        migrations.AddField(
            model_name='tbl_batch',
            name='Session_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.session'),
        ),
        migrations.AddField(
            model_name='tbl_batch',
            name='Subject_name',
            field=models.ForeignKey(limit_choices_to={'Course_name': 'Course_name'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.subject'),
        ),
        migrations.AddField(
            model_name='session',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
        ),
    ]
