# Generated by Django 4.1.6 on 2023-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0031_session_tbl_batch_remove_course_teacher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Session_category',
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Subject_name',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='tbl_Batch',
        ),
    ]
