# Generated by Django 4.1.6 on 2023-04-11 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0032_remove_tbl_batch_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_category', models.CharField(max_length=100, null=True)),
                ('session_division', models.CharField(max_length=100, null=True)),
                ('Class_teacher', models.ForeignKey(limit_choices_to={'email__type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Batch',
            fields=[
                ('c_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
                ('Session_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.session')),
                ('Subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.subject')),
            ],
        ),
    ]
