# Generated by Django 4.1.6 on 2023-04-11 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0033_session_tbl_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
