# Generated by Django 4.1.6 on 2023-04-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0037_alter_session_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_batch',
            name='Teacher_name',
            field=models.ForeignKey(limit_choices_to={'type': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
