# Generated by Django 4.1.6 on 2023-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0038_tbl_batch_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Careerprediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('df', models.CharField(blank=True, max_length=200, null=True)),
                ('ca', models.CharField(blank=True, max_length=200, null=True)),
                ('dcs', models.CharField(blank=True, max_length=200, null=True)),
                ('cs', models.CharField(blank=True, max_length=200, null=True)),
                ('networking', models.CharField(blank=True, max_length=200, null=True)),
                ('sd', models.CharField(blank=True, max_length=200, null=True)),
                ('ps', models.CharField(blank=True, max_length=200, null=True)),
                ('pm', models.CharField(blank=True, max_length=200, null=True)),
                ('cff', models.CharField(blank=True, max_length=200, null=True)),
                ('tc', models.CharField(blank=True, max_length=200, null=True)),
                ('aiml', models.CharField(blank=True, max_length=200, null=True)),
                ('se', models.CharField(blank=True, max_length=200, null=True)),
                ('ba', models.CharField(blank=True, max_length=200, null=True)),
                ('cskills', models.CharField(blank=True, max_length=200, null=True)),
                ('ds', models.CharField(blank=True, max_length=200, null=True)),
                ('td', models.CharField(blank=True, max_length=200, null=True)),
                ('gd', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
