# Generated by Django 4.1.6 on 2023-05-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0039_student_careerprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_teacher', models.ForeignKey(limit_choices_to={'type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Session_category',
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Subject_name',
        ),
        migrations.RemoveField(
            model_name='tbl_batch',
            name='Teacher_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_name',
            new_name='subject_name',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='tbl_Batch',
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.subject'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.class'),
            preserve_default=False,
        ),
    ]
