# Generated by Django 4.1.6 on 2023-05-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0042_class_teachers_teacher_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_name',
        ),
    ]
