# Generated by Django 4.1.6 on 2023-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0044_alter_class_teachers_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
