# Generated by Django 4.1.6 on 2023-02-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schoolapp', '0009_delete_tbl_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('qpaper', models.FileField(null=True, upload_to='Assignment/subject')),
                ('Subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.subjects')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
            ],
        ),
    ]
