# Generated by Django 4.1.6 on 2023-03-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_alter_tbl_assignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_assignment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
