# Generated by Django 4.1.6 on 2023-03-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0022_rename_mark_studentdetail_mark_obtained'),
        ('Teacher', '0006_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='email',
            field=models.ForeignKey(limit_choices_to={'type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login'),
        ),
    ]
