# Generated by Django 4.1.6 on 2023-03-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0022_rename_mark_studentdetail_mark_obtained'),
        ('Teacher', '0007_alter_mark_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
        ),
    ]
