# Generated by Django 4.1.6 on 2023-03-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0022_rename_mark_studentdetail_mark_obtained'),
        ('Teacher', '0008_mark_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onam_exam_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xmas_exam_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('email', models.ForeignKey(limit_choices_to={'type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.tbl_login')),
            ],
        ),
    ]
