# Generated by Django 4.1.6 on 2023-03-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_pass_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_mark',
            name='date',
        ),
    ]
