# Generated by Django 4.1.6 on 2023-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_remove_pass_mark_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_mark',
            name='id',
        ),
        migrations.AlterField(
            model_name='pass_mark',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
