# Generated by Django 4.1.6 on 2023-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_remove_pass_mark_id_alter_pass_mark_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_mark',
            name='pass_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pass_mark',
            name='pass_percentage_pred',
            field=models.FloatField(null=True),
        ),
    ]
