# Generated by Django 4.1.6 on 2023-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_pass_mark_pass_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='mark',
            name='subject1',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject3',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject4',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject5',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject6',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pass_mark',
            name='pass_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass_mark',
            name='pass_percentage_pred',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
