# Generated by Django 4.1.6 on 2023-03-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0015_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuracy',
            name='accuracy_value',
        ),
        migrations.AddField(
            model_name='accuracy',
            name='mse',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='pass_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.pass_mark'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='r2',
            field=models.FloatField(null=True),
        ),
    ]
