# Generated by Django 4.1.6 on 2023-04-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0017_pass_mark_id_alter_pass_mark_email_delete_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_mark',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='pass_mark',
            name='attendance_mark',
        ),
    ]
