# Generated by Django 4.1.6 on 2023-05-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0022_alter_pass_mark_onam_exam_marks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Assignment',
        ),
    ]
