# Generated by Django 4.1.6 on 2023-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0023_delete_tbl_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
