# Generated by Django 4.1.6 on 2023-05-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0045_exam_type'),
        ('Teacher', '0024_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('result_file', models.FileField(upload_to='Exam/Results')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.exam_type')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.subject')),
            ],
        ),
    ]
