# Generated by Django 4.1.6 on 2023-05-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0026_tbl_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
