# Generated by Django 4.1.6 on 2023-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0027_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('subject1_marks', models.IntegerField()),
                ('subject2_marks', models.IntegerField()),
                ('subject3_marks', models.IntegerField()),
                ('subject4_marks', models.IntegerField()),
                ('subject5_marks', models.IntegerField()),
                ('subject6_marks', models.IntegerField()),
            ],
        ),
    ]
